apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: varlibc
  labels:
    app: tekton
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
