apiVersion: v1
kind: Secret
metadata:
    name: sonar-propertiesssss
    annotations:
      template.openshift.io/expose-DS_KEYCLOAK_USER_PASSWORD: "{.data['DS_KEYCLOAK_USER_PASSWORD']}"
      template.openshift.io/expose-DS_SSA_SERVICE_USER_PASSWORD: "{.data['DS_SSA_SERVICE_USER_PASSWORD']}"
      template.openshift.io/expose-SSO_ADMIN_PASSWORD: "{.data['SSO_ADMIN_PASSWORD']}"
stringData:
    DS_KEYCLOAK_USER_PASSWORD: ${DS_KEYCLOAK_USER_PASSWORD}
    DS_SSA_SERVICE_USER_PASSWORD: ${DS_SSA_SERVICE_USER_PASSWORD}
    SSO_ADMIN_PASSWORD: ${SSO_ADMIN_PASSWORD}