apiVersion: v1
kind: Secret
metadata:
  name: git-basic-auth
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      username = rhiemer
      name = rodrigo.hiemer
      email = rodrigohiemer@hotmail.com
      helper = store       
  .git-credentials: |
    https://rhiemer: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@github.com