apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rollout
spec:  
  params:
   - name: git-url
     default: 'https://github.com/rhiemer/java-deployment-template.git'
   - name: git-revision
     default: 'develop'     
   - name: rollout-app-name
     default: 'java-deployment-template' 
   - name: rollout-revision
     default: 'develop'     
   - name: base-revision
     default: 'develop'
   - name: name-tag
     default: ''                      
  tasks:
    - name: generate-build-id
      taskRef:
        kind: ClusterTask
        name: generate-build-id
      params:
        - name: base-version
          value: '$(params.base-revision)'
    - name: rollout
      taskRef:
        kind: ClusterTask
        name: argocd-rollout      
      runAfter:
        - generate-build-id
      params:
        - name: APP_NAME
          value: "$(params.rollout-app-name)"
        - name: REVISION
          value: "$(params.rollout-revision)"  
    - name: git-clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      runAfter:
        - rollout
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.git-revision)"
        - name: subdirectory
          value: "$(tasks.generate-build-id.results.build-id)"
        - name: deleteExisting
          value: "true"                    
      workspaces:
        - name: output
          workspace: source-dir                  
        - name: basic-auth
          workspace: git-basic-auth
        - name: ssh-directory
          workspace: git-ssh-directory
    - name: git-tag
      taskRef:
        kind: ClusterTask
        name: git-tags
      runAfter:
        - git-clone
      params:
        - name: CONTEXT_DIR
          value: "$(tasks.generate-build-id.results.build-id)"
        - name: BUILD_ID
          value: "$(tasks.generate-build-id.results.build-id)"
        - name: NAME_TAG
          value: "$(params.name-tag)"
        - name: TAG_MESSAGE
          value: "[ci][Rollout] Rollout $(tasks.generate-build-id.results.build-id)"
      workspaces:
        - name: source
          workspace: source-dir       
        - name: basic-auth
          workspace: git-basic-auth
        - name: ssh-directory
          workspace: git-ssh-directory          
  finally:
   - name: clean-build-folders
     taskRef:
       kind: ClusterTask
       name: clear-folders
     params:
       - name: FOLDERS
         value: 
           - $(tasks.generate-build-id.results.build-id)
     workspaces:
       - name: source
         workspace: source-dir             
  workspaces:
    - name: source-dir
    - name: git-basic-auth
      optional: true   
    - name: git-ssh-directory
      optional: true   
