---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-app
spec:
  stepTemplate:
    securityContext:
      runAsUser: 0
      privileged: true
    volumeMounts:
      - name: varlibc
        mountPath: /var/lib/containers
  params:
    - name: contextDir
      description: the context dir within source
      default: .
    - name: destinationImage
      description: the fully qualified image name
      default: "image-registry.openshift-image-registry.svc:5000/devops-apps/devops-service:$(tasks.get-version.results.version)"
    - name: dockerFile
      description: the docker file to used for building the application
      default: Dockerfile
    - name: tlsVerify
      description: tls verify
      type: string
      default: "false"      
  resources:
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: build-image
      image: quay.io/buildah/stable
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      script: |
        #!/usr/bin/env bash
        set -o errexit   

        buildah bud --layers -f $(inputs.params.dockerFile) -t $(inputs.params.destinationImage) .
  volumes:
    - name: varlibc
      emptyDir: {}
