apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-java-pipeline
spec:  
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/rhiemer/devops-service.git'
        - name: revision
          value: main
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-dir
    - name: unit-tests     
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source-dir
        - name: maven-settings
          workspace: source-dir
    - name: get-infos
      runAfter:
        - junit-tests
      taskRef:
        kind: Task
        name: maven-info
      workspaces:
        - name: source
          workspace: source-dir
    - name: build-maven
      params:
        - name: SPRING_BOOT
          value: "true"
      runAfter:
        - get-version
      taskRef:
        kind: Task
        name: maven-build
      workspaces:
        - name: source
          workspace: source-dir
    - name: build-image
      params:
        - name: destinationImageTag
          value: $(tasks.get-version.results.version)
      runAfter:
        - build-maven
      taskRef:
        kind: Task
        name: buildah-build
      workspaces:
        - name: source
          workspace: source-dir
        - name: varlibc
          workspace: varlibc    
  workspaces:
    - name: source-dir
    - name: varlibc    