apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
spec:
  workspaces:
    - name: source
  params:
    - name: MAVEN_IMAGE
      type: string
      description: Maven base image
      default: gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641    
    - name: SPRING_BOOT
      type: string
      description: Maven base image
      default: "false"
    - name: CONTEXT_DIR
      type: string
      description: >-
        The context directory within the repository for sources on
        which we want to execute maven goals.
      default: "."
    - name: IMAGE_ROOT
      type: string
      description: Image root.   
      default: "registry.access.redhat.com/ubi8/openjdk-8"   
    - name: DOCKER_FILE
      type: string
      description: File build.   
      default: "Dockerfile"   
  results:
    - description: Build apps spring boot
      name: file-deploy
  steps:
    - name: mvn-command
      image: $(params.MAVEN_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)  
      script: |
        #!/usr/bin/env bash
        set -o errexit   

        _DOCKER_FILE="$(params.DOCKER_FILE)"
        if [ ! -f "${_DOCKER_FILE}"  ] ; then 
          cat > $_DOCKER_FILE << _EOF

FROM $(params.IMAGE_ROOT)



      
_EOF
        fi
