apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment-template-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-deployment-template-app
  template:
    metadata:
      labels:
        app: java-deployment-template-app
    spec:
      containers:
      - name: java-deployment-template-app
        image: java-deployment-template-app:1.0.0
        ports:
        - containerPort: 8080
