apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: deployment-app
spec:
  bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
  template:
    ref: deployment-app      