apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: deployment-app
spec:
  interceptors:
    - cel:
        overlays:
        - key: branch_name
          expression: "body.ref.split('/')[2]"
  bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
  template:
    ref: deployment-app      