apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-java-pipeline
spec:  
  params:
   - name: git-url
     type: string
     default: 'https://github.com/rhiemer/devops-service.git'
   - name: git-revision
     type: string
     default: 'main'
   - name: image-registry
     type: string
     default: 'image-registry.openshift-image-registry.svc:5000/devops-apps'    
  tasks:
    - name: rollout
      taskRef:
        kind: ClusterTask
        name: argocd-rollout
      runAfter:
        - image-push
      params:
        - name: APP_NAME
          value: "$(tasks.maven-info.results.artifactId)"
  workspaces:
    - name: source-dir
    - name: varlibc   
    - name: maven-repo
    - name: maven-settings  
    - name: sonar-settings   
