apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-service
  namespace: openshift-gitops
spec:
  destination:
    namespace: devops-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: deployment
    repoURL: https://github.com/rhiemer/devops-service.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false